 
name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Define la versión de Node.js

      - name: Instalar dependencias
        run: npm install # Instala las dependencias del proyecto

      - name: Ejecutar pruebas
        run: npm test # Ejecuta las pruebas usando Jest
